let Name = {
  hour: {
    0: "Midnight",
    1: "One",
    2: "two",
    3: "Three",
    4: "Four",
    5: "Five",
    6: "Six",
    7: "Seven",
    8: "Eight",
    9: "Nine",
    10: "Ten",
    11: "Eleven",
    12: "Twelve",
    13: "One",
    14: "Two",
    15: "Three",
    16: "Four",
    17: "Five",
    18: "Six",
    19: "Seven",
    20: "Eight",
    21: "Nine",
    22: "Ten",
    23: "Eleven",
  },
  minute: {
    1: "One",
    2: "Two",
    3: "Three",
    4: "Four",
    5: "Five",
    6: "Six",
    7: "Seven",
    8: "Eight",
    9: "Nine",
    //^^ after hour
    10: "Ten",
    11: "Eleven",
    12: "Twelve",
    13: "Thiryteen",
    14: "Fourteen",
    15: "Fifteen",
    16: "Sixteen",
    17: "Seventeen",
    18: "Eighteen",
    19: " Nineteen",
    //^^ before hour
    20: "Twenty",
    21: "Twenty One",
    22: "Twenty Two",
    23: "Twenty Three",
    24: "Twenty Four",
    27: "Twenty Seven",
    28: "Twenty Eight",
    29: "Twenty Nine",
    //^^ after hour
    30: "Thirty",
    //^^ before hour
    31: "Thirty One",
    32: "Thirty Two",
    33: "Thirty Three",
    34: "Thirty Four",
    35: "Thirty Five",
    36: "Thirty Six",
    37: "Thirty Seven",
    38: "Thirty Eight",
    39: "Thirty Nine",
    40: "Forty",
    41: "Forty One",
    42: "Forty Two",
    43: "Forty Three",
    44: "Forty Four",
    //^^ after hour
    45: "Fifteen",
    //^^ before hour and -1 hour
    46: "Forty Six",
    47: "Forty Seven",
    48: "Forty Eight",
    49: "Forty Nine",
    //^^ after hour
    50: "Fifty",
    //^^before hour and -1 hour
    51: "Fifty One",
    52: "Fifty Two",
    53: "Fifty Three",
    54: "Fifty Four",
    //^^ after hour
    55: "Fifty Five",
    // before hour and -1 hour
    56: "Fifty Six",
    57: "Fifty Seven",
    58: "Fifty Eight",
    59: "Fifty Nine",
    //^^after hour
  },
};

export default Name;
