let Name = {
  hour: {
    1: "One",
    2: "two",
    3: "Three",
    4: "Four",
    5: "Five",
    6: "Six",
    7: "Seven",
    8: "Eight",
    9: "Nine",
    10: "Ten",
    11: "Eleven",
    12: "Twelve",
    13: "Thirteen",
  },
  minute: {
    0: "",
    1: "Oh One",
    2: "Oh Two",
    3: "Oh Three",
    4: "Oh Four",
    5: "Oh Five",
    6: "Oh Six",
    7: "Oh Seven",
    8: "Oh Eight",
    9: "Oh Nine",
    //^^ after hour
    10: "Ten After",
    11: "Eleven After",
    12: "Twelve After",
    13: "Thiryteen After",
    14: "Fourteen After",
    15: "Fifteen After",
    16: "Sixteen After",
    17: "Seventeen After",
    18: "Eighteen After",
    19: " Nineteen After",
    //^^ before hour
    20: "Twenty",
    21: "Twenty One",
    22: "Twenty Two",
    23: "Twenty Three",
    24: "Twenty Four",
    27: "Twenty Seven",
    28: "Twenty Eight",
    29: "Twenty Nine",
    //^^ after hour
    30: "Half Past",
    //^^ before hour
    31: "Thirty One",
    32: "Thirty Two",
    33: "Thirty Three",
    34: "Thirty Four",
    35: "Thirty Five",
    36: "Thirty Six",
    37: "Thirty Seven",
    38: "Thirty Eight",
    39: "Thirty Nine",
    40: "Forty",
    41: "Forty One",
    42: "Forty Two",
    43: "Forty Three",
    44: "Forty Four",
    //^^ after hour
    45: "Quarter Till",
    //^^ before hour and -1 hour
    46: "Forty Six",
    47: "Forty Seven",
    48: "Forty Eight",
    49: "Forty Nine",
    //^^ after hour
    50: "Ten Till",
    //^^before hour and -1 hour
    51: "Fifty One",
    52: "Fifty Two",
    53: "Fifty Three",
    54: "Fifty Four",
    //^^ after hour
    55: "Five Till",
    // before hour and -1 hour
    56: "Fifty Six",
    57: "Fifty Seven",
    58: "Fifty Eight",
    59: "Fifty Nine",
    //^^after hour
  },
};

export default Name;
